### ISSUE TITLE
기업공지 등록/수정 페이지 리팩토링

### ISSUE THREAD

**Issue by mgYang53** [Dev-FE-2/toy-project1-team3-intranet-project#100]
## TASK 관리 명

- [ ] 매직 넘버 제거 및 상수화
- [ ] 함수 추출 및 역할 분리
- [ ] 유틸리티 함수 분리

---
### 추가 이슈
>
