### ISSUE TITLE
공통 assets 추가

### ISSUE THREAD

**Issue by mgYang53** [Dev-FE-2/toy-project1-team3-intranet-project#110]
## TASK 관리 명

- [x] 이미지 및 css 파일 위치 변경
- [x] 공통 css 변수 추가
- [x] 공통 폰트 추가

---
### 추가 이슈
>
