### ISSUE TITLE
기업공지 상세 페이지 기능 개발

### ISSUE THREAD

**Issue by mgYang53** [Dev-FE-2/toy-project1-team3-intranet-project#48]
## TASK 관리 명

- [x] 기업공지 상세 API 생성
- [x] 기업공지 삭제 API 생성
- [x] 기업공지 상세 데이터 연동
- [x] 이미지 불러오기

---
### 추가 이슈
> 이미지 불러오기는 공지 등록 기능 이후 작업 예정

**Comment by mgYang53** [comment]
이미지 불러오기 기능 개발 후 close 예정
