### ISSUE TITLE
사용자 권한(userGrade)에 따른 네비게이션 바 출력 조건문 수정

### ISSUE THREAD

**Issue by laivastia** [Dev-FE-2/toy-project1-team3-intranet-project#88]
## TASK 관리 명

- [x] fix : 사용자 권한 정보에 맞춰 렌더링 되는 네비게이션 바 형식 변경
- [x] rename : shortCut에서 navigate로 명칭 변경
- [x] refact : 삼항연산자를 사용한 변수형태 에서 함수 - 조건식 형태 렌더링으로 변경

---
### 추가 이슈
>
