### ISSUE TITLE
기업공지 상세 페이지 리팩토링

### ISSUE THREAD

**Issue by mgYang53** [Dev-FE-2/toy-project1-team3-intranet-project#98]
## TASK 관리 명

- [x] 매직넘버 제거 및 상수화
- [x] 상태 관리 객체 추가
- [x] 함수 추출 및 역할 분리

---
### 추가 이슈
>
